name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check runner
        run: |
          echo "Running on EC2 self-hosted runner"
          docker --version
          trivy --version
